### ISSUE TITLE
Hi ran into a bug, can you help?

### ISSUE THREAD

**Issue by ArtemDziubeilo** [alpdias/calendario-economico-python-bot#1]
Hi, I created a test bot in Telegram for the code test, tied it to a public group, on startup I get an error screenshot below, as I read this error occurred on older versions of the Teleport module, but I think that most likely I have an error somewhere, do you know what it could be related to?
![2](https://user-images.githubusercontent.com/118462423/207384468-b0d3aa2f-4cae-404a-9465-823a466df54a.png)

**Comment by alpdias** [comment]
Hello @ArtemDziubeilo, how are you!? Nice to be using my script and the telepot, sorry but at the moment I can't help you, I hope you can find a solution to your problem. Thanks!
